
stages:
  - build

build:linux:amd64:
  stage: build
  script:
    - export CI_OS=linux
    - export CI_ARCH=amd64
    - scripts/ci-build-linux.sh
  tags:
    - dropsy

build:windows:386:
  stage: build
  script:
    - export CI_OS=windows
    - export CI_ARCH=386
    - scripts/ci-build-windows.sh
  tags:
    - windows

build:darwin:amd64:
  stage: build
  script:
    - export CI_OS=darwin
    - export CI_ARCH=amd64
    - scripts/ci-build-darwin.sh
  tags: 
    - darwin

