
stages:
  - build

build:linux:amd64:
  stage: build
  script:
    - export CI_ARCH=amd64
    - scripts/ci-build-linux.sh

build:windows:i386:
  stage: build
  script:
    - export CI_ARCH=i386
    - scripts/ci-build-windows.sh
  tags:
    - windows

build:darwin:amd64:
  stage: build
  script:
    - export CI_ARCH=amd64
    - scripts/ci-build-darwin.sh
  tags: 
    - darwin

