
stages:
  - build
  - deploy

build:linux:386:
  stage: build
  script:
    - export CI_OS=linux
    - export CI_ARCH=386
    - scripts/ci-build.sh
  tags:
    - docker-itchsetup-32
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:linux:amd64:
  stage: build
  script:
    - export CI_OS=linux
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
  tags:
    - docker-itchsetup-64
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:windows:386:
  stage: build
  script:
    - export CI_OS=windows
    - export CI_ARCH=386
    - scripts/ci-build.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:windows:amd64:
  stage: build
  script:
    - export CI_OS=windows
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - broth

build:darwin:amd64:
  stage: build
  script:
    - export CI_OS=darwin
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
  tags: 
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - broth

deploy:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-deploy.sh
